apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - url
                - replicas
              properties:
                url:
                  type: string
                  description: "웹사이트의 URL"
                  example: "https://example.com"
                replicas:
                  type: integer
                  description: "배포할 복제본 수"
                  minimum: 1
                  maximum: 10
                  default: 3
                image:
                  type: string
                  description: "사용할 Docker 이미지"
                  default: "nginx:latest"
                port:
                  type: integer
                  description: "컨테이너 포트"
                  default: 80
                  minimum: 1
                  maximum: 65535
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer
                  description: "사용 가능한 복제본 수"
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
  scope: Namespaced
  names:
    plural: websites
    singular: website
    kind: Website
    shortNames:
    - ws
    categories:
    - all
