apiVersion: example.com/v1
kind: Website
metadata:
  name: my-website
  namespace: default
  labels:
    app: my-website
    environment: development
spec:
  url: "https://my-website.example.com"
  replicas: 5
  image: "nginx:alpine"
  port: 8080
